# -*- coding: utf-8 -*-
"""temp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PsjZuLrj5C1WMWNKCO1ehdZYC8A2IPuW
"""

from keras.models import load_model
from joblib import load
from keras_preprocessing.sequence import pad_sequences

# Load the pre-trained model and tokenizer
model = load_model("model/model.h5")
tokenizer = load("model/tokenizer.pkl")

# Define constants
SEQUENCE_LENGTH = 300
SENTIMENT_THRESHOLDS = (0.4, 0.7)

def predict(text):
    # Use the tokenizer to convert the text into a sequence
    sequence = tokenizer.texts_to_sequences([text])
    sequence = pad_sequences(sequence, maxlen=SEQUENCE_LENGTH)

    # Use the model to make a prediction
    prediction = model.predict(sequence)
    score = prediction[0][0]

    # Decode the sentiment
    if score < SENTIMENT_THRESHOLDS[0]:
        label = "NEGATIVE"
    elif score < SENTIMENT_THRESHOLDS[1]:
        label = "NEUTRAL"
    else:
        label = "POSITIVE"

    return {"label": label, "score": score}

# Example usage
print(predict("I am definitely with chatgpt."))

